# Generated by Django 2.1.4 on 2022-03-16 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
