# Generated by Django 2.1.4 on 2022-03-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0002_auto_20220316_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Posts'},
        ),
    ]
