# Generated by Django 3.0.5 on 2022-03-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0005_auto_20220317_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default='SOME QUOTE')),
            ],
            options={
                'verbose_name_plural': 'Quotes',
            },
        ),
    ]
