# Generated by Django 3.0.5 on 2022-03-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0006_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='img_link',
            field=models.TextField(default='SOME QUOTE'),
        ),
    ]
