# Generated by Django 3.0.5 on 2022-03-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0008_auto_20220322_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='img_link',
            field=models.TextField(default='SOME IMG'),
        ),
    ]
