# Generated by Django 3.0.5 on 2022-03-28 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0009_posts_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
