# Generated by Django 3.0.5 on 2022-03-30 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0011_auto_20220330_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
