# Generated by Django 3.0.5 on 2022-04-03 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0012_auto_20220330_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 18, 28, 54, 988731, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 18, 28, 54, 989016, tzinfo=utc)),
        ),
    ]
