# Generated by Django 3.0.5 on 2022-04-03 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0014_auto_20220403_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
